"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const adminControllers_1 = require("../controllers/adminControllers");
const router = (0, express_1.Router)();
router.get("/bus", adminControllers_1.getBuses);
router.get("/bus/details/:id", adminControllers_1.getBusdetails);
router.post("/bus/create", adminControllers_1.createBus);
router.put("/bus/add-trip/:id", adminControllers_1.updateBus);
router.put("/ticket-reset/:id", adminControllers_1.resetTickets);
exports.default = router;
